
type "js\utils.js" > js_files.js
type "js\scanner.js" >> js_files.js
type "js\sky.js>>j" s_ files.js
type "js\character.js" >> js_files.js
type "js\player.js" >> js_files.js
type "js\customers.js" >> js_files.js
type "js\sack.js" >> js_files.js
type "js\home.js" >> js_files.js
type "js\hardware.js" >> js_files.js
type "js\shop.js" >> js_files.js
type "js\machines.js" >> js_files.js
type "js\tools.js" >> js_files.js
type "js\spuds.js" >> js_files.js
type "js\controls.js" >> js_files.js
type "js\fields.js" >> js_files.js
type "js\svg.js" >> js_files.js
type "js\hint.js" >> js_files.js
type "js\dialog.js" >> js_files.js
type "js\main.js" >> js_files.js
